In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [3]:
x = []
x

[]

In [4]:
x = [1, 2, 3]

In [5]:
x

[1, 2, 3]

In [6]:
x[1]

2

In [7]:
x[0]

1

In [10]:
x = [[1, 2], [3, 4]]

In [11]:
x

[[1, 2], [3, 4]]

In [14]:
x[0][0]

1

In [48]:
x = [1, 'one']

In [49]:
x

[1, 'one']

In [50]:
for i in range(0, 10):
    x.append(i)


In [51]:
x

[1, 'one', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
sum(x)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [53]:
z = []
for i in range(0, 10):
    z.append(x.pop())
    print(x)
    print(z)

[1, 'one', 0, 1, 2, 3, 4, 5, 6, 7, 8]
[9]
[1, 'one', 0, 1, 2, 3, 4, 5, 6, 7]
[9, 8]
[1, 'one', 0, 1, 2, 3, 4, 5, 6]
[9, 8, 7]
[1, 'one', 0, 1, 2, 3, 4, 5]
[9, 8, 7, 6]
[1, 'one', 0, 1, 2, 3, 4]
[9, 8, 7, 6, 5]
[1, 'one', 0, 1, 2, 3]
[9, 8, 7, 6, 5, 4]
[1, 'one', 0, 1, 2]
[9, 8, 7, 6, 5, 4, 3]
[1, 'one', 0, 1]
[9, 8, 7, 6, 5, 4, 3, 2]
[1, 'one', 0]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 'one']
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [22]:
x = [1, 2, 3]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

In [54]:
z

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [55]:
for Z in z:
    print(Z)

9
8
7
6
5
4
3
2
1
0


In [56]:
s = "im a string"

In [57]:
s

'im a string'

In [58]:
S = 'IM ALSO A STRING'

In [59]:
S

'IM ALSO A STRING'

In [60]:
s[0]

'i'

In [61]:
for i in S:
    print(i)

I
M
 
A
L
S
O
 
A
 
S
T
R
I
N
G


In [63]:
S.lower()

'im also a string'

In [65]:
s[0] = 'I'

TypeError: 'str' object does not support item assignment

In [66]:
s[0].upper()

'I'

In [68]:
s = 'Im a string'

In [69]:
s

'Im a string'

In [70]:
s.lower()

'im a string'

In [71]:
s.find('a')

3

In [72]:
s[-1]

'g'

In [73]:
s[-5]

't'

In [74]:
T = (0, 1)

In [76]:
T

(0, 1)

In [77]:
T[0]

0

In [78]:
T[0] = 1

TypeError: 'tuple' object does not support item assignment

In [79]:
T.append(1)

AttributeError: 'tuple' object has no attribute 'append'

In [80]:
D = {'homeworks': [1, 2, 3],
     'grades': [0,0,0]}

In [81]:
D

{'grades': [0, 0, 0], 'homeworks': [1, 2, 3]}

In [82]:
D['grades']

[0, 0, 0]

In [83]:
type(D)

dict

In [84]:
for i in D:
    print(i)

grades
homeworks


In [94]:
for i, j in enumerate(D['homeworks']):
    print(i, j)
    print(D['grades'][i])

0 1
0
1 2
0
2 3
0


In [95]:
D

{'grades': [0, 0, 0], 'homeworks': [1, 2, 3]}

In [96]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [97]:
import numpy as np

In [104]:
x = np.zeros([2, 2])

In [105]:
x

array([[ 0.,  0.],
       [ 0.,  0.]])

In [106]:
I = np.eye((2))

In [107]:
I

array([[ 1.,  0.],
       [ 0.,  1.]])

In [109]:
I[0, 0]

1.0

In [112]:
x = np.array([1.0, '2.0'])
x

array(['1.0', '2.0'], 
      dtype='<U32')

In [113]:
x = np.zeros((2,2,2,2,2,2,2,2,2,2))

In [115]:
x.shape

(2, 2, 2, 2, 2, 2, 2, 2, 2, 2)

In [116]:
x

array([[[[[[[[[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]],


             [[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]]],



            [[[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]],


             [[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]]]],




           [[[[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]],


             [[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]]],



            [[[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]],


             [[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0.,  0.],
               [ 0.,  0.]]]]]],





          [[[[[[ 0.,  0.],
               [ 0.,  0.]],

              [[ 0

In [125]:
X = np.array((range(0, 10),range(10,20)))

In [126]:
X[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [130]:
X[:, 0]

array([ 0, 10])

In [132]:
X[:, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [137]:
print(2 % 2 == 1)
3 % 2 == 1

False


True

In [139]:
X % 2 == 0

array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]], dtype=bool)

In [142]:
X[X != 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [143]:
a = np.eye((2))

In [144]:
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [146]:
b = a

In [148]:
b

array([[ 1.,  0.],
       [ 0.,  1.]])

In [149]:
a[0, 0] = 0

In [151]:
a

array([[ 0.,  0.],
       [ 0.,  1.]])

In [153]:
b

array([[ 0.,  0.],
       [ 0.,  1.]])

In [170]:
a = np.eye((2))


In [171]:
print(a)
b[:] = a
print(b)

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]


In [172]:
a[0, 0] = 0
print(a)
print(b)

[[ 0.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]


In [177]:
a = np.array((0, 1, 2))

In [183]:
b = np.zeros((3, 3, 4))

In [184]:
print(a)
print(b)

[0 1 2]
[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [185]:
a.shape

(3,)

In [187]:
b.shape

(3, 3, 4)

In [191]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,3,4) 

In [190]:
a[:, np.newaxis] + b

array([[[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.]],

       [[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.]],

       [[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.]]])

In [194]:
a[np.newaxis, :] * b

ValueError: operands could not be broadcast together with shapes (1,3) (3,3,4) 